<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="G-0439" name="orion3_Navigation.OpsAdminTab" tests="7" failures="0" timestamp="24 Mar 2015 09:00:07 GMT" time="44.155" errors="1">
  <testcase name="verifyStudentSuccessManager" time="11.186" classname="orion3_Navigation.OpsAdminTab">
    <error type="java.lang.AssertionError" message="Left Name plate is NOT appearing as expected expected [KHE ORION 3 &gt; Ops Admin &gt; Student Success Manager] but found []">
      <![CDATA[java.lang.AssertionError: Left Name plate is NOT appearing as expected expected [KHE ORION 3 > Ops Admin > Student Success Manager] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at orion3_Navigation.OpsAdminTab.verifyStudentSuccessManager(OpsAdminTab.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- verifyStudentSuccessManager -->
  <testcase name="verifyEmailTemplateMgrPostEnroll" time="5.357" classname="orion3_Navigation.OpsAdminTab"/>
  <testcase name="verifyARA_ManageTiers" time="6.052" classname="orion3_Navigation.OpsAdminTab"/>
  <testcase name="verifyIQM_CancelLeadTransfer" time="3.100" classname="orion3_Navigation.OpsAdminTab"/>
  <testcase name="verifyIQM_LeadTransfer" time="2.993" classname="orion3_Navigation.OpsAdminTab"/>
  <testcase name="verifyALCCampaignManagerUploadLeads" time="4.935" classname="orion3_Navigation.OpsAdminTab"/>
  <testcase name="verifyEmailTemplateMgrAdmissions" time="10.532" classname="orion3_Navigation.OpsAdminTab"/>
</testsuite> <!-- orion3_Navigation.OpsAdminTab -->
