<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PARORA-LAPTOP" name="KUPortal_TopNavigation_CHROME" tests="6" failures="3" timestamp="5 Dec 2014 15:00:34 GMT" time="66.711" errors="0">
  <testcase name="CheckHome" time="2.707" classname="KuPortal.Test_HomePage"/>
  <testcase name="CheckMyStudies" time="11.945" classname="KuPortal.Test_HomePage"/>
  <testcase name="AboutKaplanUniversity" time="2.793" classname="KuPortal.Test_LandingPage"/>
  <testcase name="LinkReference_LandingPage" time="6.84" classname="KuPortal.Test_LandingPage">
    <failure type="java.lang.AssertionError" message="Failure Count is not 0. Please check the Reporter log for failed items expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: Failure Count is not 0. Please check the Reporter log for failed items expected [0] but found [2]
	at KuPortal.Test_LandingPage.LinkReference_LandingPage(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LinkReference_LandingPage -->
  <testcase name="LinkReference_LandingPage" time="6.61" classname="KuPortal.Test_LandingPage">
    <failure type="java.lang.AssertionError" message="Failure Count is not 0. Please check the Reporter log for failed items expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: Failure Count is not 0. Please check the Reporter log for failed items expected [0] but found [2]
	at KuPortal.Test_LandingPage.LinkReference_LandingPage(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LinkReference_LandingPage -->
  <testcase name="LinkReference_LandingPage" time="5.526" classname="KuPortal.Test_LandingPage">
    <failure type="java.lang.AssertionError" message="Failure Count is not 0. Please check the Reporter log for failed items expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: Failure Count is not 0. Please check the Reporter log for failed items expected [0] but found [2]
	at KuPortal.Test_LandingPage.LinkReference_LandingPage(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- LinkReference_LandingPage -->
</testsuite> <!-- KUPortal_TopNavigation_CHROME -->
